title: On the verge
author: smarliecy
email: email@hotmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  what I want to write

# social links
twitter_username: smarlie # DO NOT include the @ character, or else the build will fail!
github_username:  smarliecy # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
